language: node_js
node_js:
  - lts/*
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker build -t niass/docker-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run niass/docker-react-test npm run test -- --coverage

after_script:
  - docker build -t niass/multi-client ./client
  - docker build -t niass/multi-nginx ./nginx
  - docker build -t niass/multi-server ./server 
  - docker build -t niass/multi-worker ./worker 
  # login in to docker
  # Push images to docker
  - docker push niass/multi-client
  - docker push niass/multi-nginx
  - docker push niass/multi-server
  - docker push niass/multi-worker
