language: node_js
node_js:
  - lts/*
services:
  - docker
before_install:
  - docker build -t niass/docker-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run niass/docker-react-test npm run test -- --coverage

after_success:
  - travis_wait 40 docker build -t niass/multi-client ./client
  -  travis_wait 40docker build -t niass/multi-nginx ./nginx
  -  travis_wait 40docker build -t niass/multi-server ./server 
  - travis_wait 40 docker build -t niass/multi-worker ./worker 
  # login in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Push images to docker
  - docker push niass/multi-client
  - docker push niass/multi-nginx
  - docker push niass/multi-server
  - docker push niass/multi-worker
